import { Activity, ArrowRight, Blocks, Database, ExternalLink, FileCheck2, Fingerprint, HardDrive, Layers3, LockKeyhole, ShieldCheck, Workflow, Zap } from 'lucide-react';
import type { PlatformHealth } from '@nita/contracts';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { RefreshButton } from './refresh-button';

const phases = [
  { number: '01', title: 'Technical Clearance', note: 'Assess & authorize', icon: FileCheck2 },
  { number: '02', title: 'Project Implementation', note: 'Deliver & oversee', icon: Layers3 },
  { number: '03', title: 'UAT & Technical Conformity', note: 'Test & validate', icon: ShieldCheck },
  { number: '04', title: 'Certificate of Conformity', note: 'Certify & record', icon: Fingerprint },
];
export function PlatformOverview({ health, docsUrl }: { health: PlatformHealth; docsUrl: string }) {
  const available = health.status !== 'unavailable';
  const healthy = health.status === 'ok';
  const infrastructure = [
    { title: 'PostgreSQL', label: 'Integrated database', icon: Database, state: health.checks.database },
    { title: 'Redis', label: 'Shared cache', icon: Zap, state: health.checks.redis },
    { title: 'Object storage', label: 'MinIO · S3 compatible', icon: HardDrive, state: health.checks.storage },
  ];
  return <div className="min-h-screen bg-[#f5f7fa] text-foreground">
    <aside className="fixed inset-y-0 left-0 hidden w-60 flex-col bg-[#0d243f] text-slate-300 lg:flex">
      <a href="#overview" className="flex items-center gap-3 border-b border-white/10 px-6 py-7 text-white"><div className="flex size-11 items-center justify-center rounded-xl bg-white/10"><ShieldCheck className="size-7 text-[#d9ba70]" /></div><div><div className="text-xl font-bold tracking-[.12em]">NITA</div><div className="text-[10px] text-slate-400">GOVERNMENT OF GHANA</div></div></a>
      <div className="px-6 pt-7 text-[10px] font-semibold tracking-[.16em] text-slate-500">PLATFORM</div>
      <nav aria-label="Platform navigation" className="space-y-2 p-4"><a href="#overview" className="flex items-center gap-3 rounded-lg bg-white/10 px-4 py-3 text-sm font-medium text-white"><Blocks className="size-4 text-[#d9ba70]" />Overview</a><a href="#health" className="flex items-center gap-3 rounded-lg px-4 py-3 text-sm hover:bg-white/5"><Activity className="size-4" />Platform health</a><a href={docsUrl} className="flex items-center gap-3 rounded-lg px-4 py-3 text-sm hover:bg-white/5"><FileCheck2 className="size-4" />API documentation<ExternalLink className="ml-auto size-3" /></a></nav>
      <div className="mx-5 mt-auto mb-6 rounded-xl border border-white/10 p-4"><div className="mb-2 text-xs font-medium text-white">Core platform · Module 0</div><p className="text-xs leading-5 text-slate-400">The shared foundation for Ghana’s ICT project assurance lifecycle.</p><div className="mt-4 flex items-center gap-2 text-[10px] text-slate-400"><span className="size-1.5 rounded-full bg-[#d9ba70]" />Development environment</div></div>
    </aside>
    <div className="lg:ml-60">
      <header className="flex min-h-18 flex-wrap items-center justify-between gap-3 border-b border-border bg-white px-5 py-4 sm:px-9"><div className="text-xs text-slate-500"><span className="font-medium text-slate-800">National Information Technology Agency</span><span className="mx-3 hidden sm:inline">/</span><span className="hidden sm:inline">Technical Services</span></div><Badge className="border-[#e2d6b8] bg-[#faf6eb] text-[#816b30]">Module 0 · Foundation</Badge></header>
      <main id="overview" className="mx-auto max-w-7xl px-5 py-8 sm:px-9 sm:py-10">
        <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><div className="mb-3 text-[10px] font-semibold tracking-[.18em] text-slate-500">TECHNICAL CLEARANCE & CONFORMITY MANAGEMENT</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Platform overview</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">One integrated platform for government ICT project assurance, from technical clearance through certification.</p></div><RefreshButton /></div>
        <section aria-labelledby="lifecycle-heading" className="mb-7 overflow-hidden rounded-2xl bg-[#102b49] p-6 text-white sm:p-7"><div className="mb-6 flex items-center justify-between gap-4"><div><div className="mb-2 text-[10px] font-semibold tracking-[.17em] text-[#d9ba70]">THE OFFICIAL LIFECYCLE</div><h2 id="lifecycle-heading" className="text-lg font-medium">One project. A connected assurance journey.</h2></div><Workflow className="hidden size-8 text-white/30 sm:block" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{phases.map((phase, index) => <div key={phase.number} className="relative rounded-xl border border-white/10 bg-white/[.035] p-4"><div className="mb-5 flex items-center justify-between"><phase.icon className="size-5 text-[#d9ba70]" /><span className="text-xs text-white/30">{phase.number}</span></div><div className="min-h-10 text-sm font-medium leading-5">{phase.title}</div><div className="mt-2 text-xs text-slate-400">{phase.note}</div>{index < phases.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-4 text-[#d9ba70] xl:block" />}</div>)}</div><p className="mt-5 text-xs text-slate-400">Shared Project ID, records and audit history across every phase. Business modules will be introduced in later development stages.</p></section>
        <section id="health" aria-labelledby="health-heading"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 id="health-heading" className="text-base font-semibold">Platform health</h2><div aria-live="polite" className="flex items-center gap-2 text-xs text-slate-500"><span className={`size-2 rounded-full ${healthy ? 'bg-emerald-500' : 'bg-amber-500'}`} />{healthy ? 'All dependencies operational' : available ? 'Dependency attention required' : 'API health response unavailable'}</div></div><div className="grid gap-4 md:grid-cols-3">{infrastructure.map(service => <Card key={service.title}><CardHeader className="flex flex-row items-center justify-between"><div className="flex size-10 items-center justify-center rounded-lg bg-slate-100 text-[#234a73]"><service.icon className="size-5" /></div><Badge className={service.state === 'up' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : 'border-amber-100 bg-amber-50 text-amber-700'}>{service.state === 'up' ? 'Operational' : available ? 'Unavailable' : 'Not verified'}</Badge></CardHeader><CardContent><CardTitle>{service.title}</CardTitle><p className="mt-2 text-xs text-slate-500">{service.label}</p></CardContent></Card>)}</div><p className="mt-3 text-[11px] text-slate-400">{available ? 'Checked' : 'Attempted'} {new Date(health.timestamp).toISOString().replace('T', ' ').slice(0, 19)} UTC · Live dependency checks</p></section>
        <div className="mt-7 grid gap-5 xl:grid-cols-[1.3fr_1fr]"><Card><CardHeader><CardTitle>Common platform capabilities</CardTitle></CardHeader><CardContent><div className="divide-y divide-slate-100">{[{ icon: Database, name: 'One authoritative project identity', description: 'Shared references across the integrated schema' }, { icon: Workflow, name: 'Central workflow engine', description: 'Guarded transitions, evidence and decision history' }, { icon: LockKeyhole, name: 'Authentication architecture', description: 'OIDC compatible · Keycloak-ready · MFA-ready' }].map(item => <div key={item.name} className="flex gap-3 py-4"><item.icon className="mt-0.5 size-4 shrink-0 text-slate-400" /><div><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p></div></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Governance built into the foundation</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-slate-500">Recommendations, Director-General decisions and certificate issuance remain distinct actions.</p><div className="my-5 rounded-lg border border-slate-100 bg-slate-50 p-4"><div className="mb-2 text-xs font-semibold text-slate-700">External verification · Read-only</div><p className="text-xs leading-5 text-slate-500">PPA verifies Technical Clearance only. Ministry of Finance verifies Technical Clearance and Certificates of Conformity.</p></div><Button asChild variant="outline" size="sm"><a href={docsUrl}>Explore platform API<ExternalLink className="size-3.5" /></a></Button></CardContent></Card></div>
        <footer className="mt-10 flex flex-wrap justify-between gap-2 border-t border-border pt-5 text-[11px] text-slate-400"><span>NITA · Technical Clearance and Conformity Management System</span><span>Integrated platform · v0.1.0</span></footer>
      </main>
    </div>
  </div>;
}
