import assert from 'node:assert/strict';
const backend = process.env.BACKEND_URL || 'http://localhost:4000';
const frontend = process.env.FRONTEND_URL || 'http://localhost:3000';
const request = url => fetch(url, { signal: AbortSignal.timeout(10000) });
const ready = await request(`${backend}/api/v1/health/ready`);
assert.equal(ready.status, 200);
assert.deepEqual((await ready.json()).checks, { database: 'up', redis: 'up', storage: 'up' });
const live = await request(`${backend}/api/v1/health/live`);
assert.equal(live.status, 200);
const openapi = await request(`${backend}/api/v1/openapi.json`);
assert.equal(openapi.status, 200);
assert.ok((await openapi.json()).paths['/api/v1/health/ready']);
const validation = await request(`${backend}/api/v1/platform?detail=invalid`);
assert.equal(validation.status, 400);
assert.ok((await validation.json()).correlationId);
const web = await request(frontend);
assert.equal(web.status, 200);
const html = await web.text();
assert.ok(html.includes('Platform overview'));
assert.ok(html.includes('All dependencies operational'));
assert.equal((await request(`${frontend}/health`)).status, 200);
console.log('PASS: dependency readiness, API liveness, OpenAPI, validation, frontend live dependency rendering and frontend liveness.');
